#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import PoseStamped
from tf2_ros import TransformBroadcaster
from geometry_msgs.msg import TransformStamped


class MocapTFBridge(Node):

    def __init__(self):
        super().__init__('mocap_tf_bridge')

        self.declare_parameter("rigid_body_name", "cf231")
        self.rigid_body_name = self.get_parameter(
            "rigid_body_name").value

        self.subscription = self.create_subscription(
            PoseStamped,
            f'/{self.rigid_body_name}/pose',
            self.pose_callback,
            10
        )

        self.tf_broadcaster = TransformBroadcaster(self)

    def pose_callback(self, msg):

        t = TransformStamped()
        t.header.stamp = self.get_clock().now().to_msg()
        t.header.frame_id = "world"
        t.child_frame_id = self.rigid_body_name

        t.transform.translation.x = msg.pose.position.x
        t.transform.translation.y = msg.pose.position.y
        t.transform.translation.z = msg.pose.position.z

        t.transform.rotation = msg.pose.orientation

        self.tf_broadcaster.sendTransform(t)


def main(args=None):
    rclpy.init(args=args)
    node = MocapTFBridge()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
